# Generated by Django 4.2.3 on 2023-07-25 10:32

from django.db import migrations, models
import django.db.models.deletion
import django_tenants.postgresql_backend.base


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('schema_name', models.CharField(db_index=True, max_length=63, unique=True, validators=[django_tenants.postgresql_backend.base._check_schema_name])),
                ('name', models.CharField(max_length=64, verbose_name='租户名称')),
                ('contact_person', models.CharField(max_length=32, verbose_name='联系人')),
                ('contact_email', models.CharField(max_length=64, verbose_name='联系邮箱')),
                ('contact_phone', models.CharField(max_length=32, verbose_name='联系电话')),
                ('status', models.IntegerField(choices=[(0, '审核中'), (1, '正常'), (2, '禁用')], default=1, verbose_name='租户状态')),
                ('expire_date', models.DateTimeField(verbose_name='过期时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注')),
            ],
            options={
                'verbose_name': '租户',
                'verbose_name_plural': '租户',
                'db_table': 'win_tenant',
            },
        ),
        migrations.CreateModel(
            name='Domain',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('domain', models.CharField(db_index=True, max_length=253, unique=True)),
                ('is_primary', models.BooleanField(db_index=True, default=True)),
                ('tenant', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='domains', to='platforms.tenant')),
            ],
            options={
                'verbose_name': '域名',
                'verbose_name_plural': '域名',
                'db_table': 'win_domain',
            },
        ),
    ]
