# Generated by Django 4.2.3 on 2023-09-12 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0002_systempost_systemdept'),
    ]

    operations = [
        migrations.AlterField(
            model_name='systemdept',
            name='creator',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='创建者'),
        ),
    ]
