# Generated by Django 4.2.3 on 2023-09-25 14:20

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_alter_systemdept_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemconfigtab',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='systemconfigtab',
            name='creator',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='创建者'),
        ),
        migrations.AddField(
            model_name='systemconfigtab',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, verbose_name='更新时间'),
        ),
        migrations.AddField(
            model_name='systemconfigtab',
            name='updater',
            field=models.CharField(blank=True, max_length=64, null=True, verbose_name='更新者'),
        ),
    ]
