# Generated by Django 4.2.3 on 2023-09-27 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0005_systemconfig_created_at_systemconfig_creator_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='systemconfig',
            old_name='name',
            new_name='label',
        ),
        migrations.AlterField(
            model_name='systemconfig',
            name='type',
            field=models.CharField(choices=[('input', '输入框'), ('number', '数字输入框'), ('textarea', '文本域'), ('select', '下拉选择框'), ('radio', '单选框'), ('checkbox', '复选框'), ('date', '日期'), ('time', '时间'), ('datetime', '日期+时间'), ('datetime-to-datetime', '时间区间'), ('cascader', '级联'), ('switch', '开关')], default='Input', max_length=64, verbose_name='字段类型'),
        ),
    ]
