# Generated by Django 4.2.3 on 2023-12-12 15:41

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0009_remove_dictdata_end_at_remove_dictdata_updated_by_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='SystemMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64, verbose_name='菜单名称')),
                ('type', models.IntegerField(choices=[(1, '模块'), (2, '导航'), (3, '菜单'), (4, '节点')], default=3, verbose_name='菜单类型')),
                ('permission', models.CharField(max_length=128, verbose_name='权限标识')),
                ('path', models.CharField(blank=True, max_length=255, null=True, verbose_name='路由地址')),
                ('icon', models.CharField(blank=True, max_length=32, null=True, verbose_name='菜单图标')),
                ('href', models.CharField(blank=True, max_length=128, null=True, verbose_name='API接口地址')),
                ('method', models.CharField(blank=True, choices=[('1', 'POST'), ('2', 'GET'), ('3', 'PUT'), ('4', 'DELETE'), ('5', 'PATCH')], max_length=32, null=True, verbose_name='请求方法')),
                ('params', models.CharField(blank=True, max_length=255, null=True, verbose_name='请求参数')),
                ('sort', models.IntegerField(default=0, verbose_name='排序')),
                ('is_hidden', models.IntegerField(default=0, verbose_name='是否隐藏')),
                ('redirect', models.CharField(blank=True, max_length=255, null=True, verbose_name='重定向')),
                ('component', models.CharField(blank=True, max_length=128, null=True, verbose_name='组件路径')),
                ('target', models.SmallIntegerField(choices=[(0, '组件'), (1, '内链'), (2, '外链')], default=0)),
                ('remark', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('creator', models.CharField(blank=True, max_length=64, null=True, verbose_name='创建者')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('updater', models.CharField(blank=True, max_length=64, null=True, verbose_name='更新者')),
                ('status', models.IntegerField(choices=[(0, '禁用'), (1, '正常')], default=1, verbose_name='菜单状态')),
                ('lft', models.PositiveIntegerField(editable=False)),
                ('rght', models.PositiveIntegerField(editable=False)),
                ('tree_id', models.PositiveIntegerField(db_index=True, editable=False)),
                ('level', models.PositiveIntegerField(editable=False)),
                ('parent', mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='children', to='system.systemmenu', verbose_name='上级目录')),
            ],
            options={
                'verbose_name': '菜单',
                'verbose_name_plural': '菜单',
                'db_table': 'win_system_menu',
                'unique_together': {('name', 'permission')},
            },
        ),
        migrations.CreateModel(
            name='SystemRoleMenu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('menu_id', models.ForeignKey(help_text='关联菜单', on_delete=django.db.models.deletion.CASCADE, related_name='role_menu', to='system.systemmenu')),
                ('role_id', models.ForeignKey(help_text='关联角色', on_delete=django.db.models.deletion.CASCADE, related_name='role_menu', to='system.systemrole')),
            ],
            options={
                'verbose_name': '角色菜单',
                'verbose_name_plural': '角色菜单',
                'db_table': 'win_system_role_menu',
            },
        ),
    ]
