# Generated by Django 4.2.3 on 2023-08-04 10:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True, verbose_name='操作时间')),
                ('operation_model', models.CharField(max_length=100, verbose_name='操作模块')),
                ('operation_object', models.CharField(max_length=100, verbose_name='操作对象')),
                ('operation_action', models.CharField(max_length=100, verbose_name='操作类型')),
                ('request_method', models.CharField(max_length=10, verbose_name='请求方法名')),
                ('request_path', models.CharField(max_length=200, verbose_name='请求地址')),
                ('request_data', models.TextField(verbose_name='请求数据')),
                ('response_data', models.TextField(verbose_name='响应数据')),
                ('response_status_code', models.PositiveIntegerField(verbose_name='响应码')),
                ('user_ip', models.GenericIPAddressField(verbose_name='用户IP')),
                ('user_agent', models.CharField(max_length=200, verbose_name='浏览器UA')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '操作日志',
                'verbose_name_plural': '操作日志',
                'db_table': 'win_audit_log',
            },
        ),
    ]
