# Generated by Django 4.2.3 on 2023-07-14 11:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CasbinRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ptype', models.CharField(max_length=255)),
                ('v0', models.CharField(max_length=255)),
                ('v1', models.CharField(max_length=255)),
                ('v2', models.CharField(blank=True, max_length=255, null=True)),
                ('v3', models.CharField(blank=True, max_length=255, null=True)),
                ('v4', models.CharField(blank=True, max_length=255, null=True)),
                ('v5', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': '权限策略',
                'verbose_name_plural': '权限策略',
                'db_table': 'casbin_rule',
                'unique_together': {('ptype', 'v0', 'v1', 'v2')},
            },
        ),
    ]
