# Generated by Django 4.2.3 on 2023-07-26 16:06

from django.conf import settings
import django.contrib.auth.models
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='WaUser',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('first_name', models.CharField(blank=True, max_length=150, verbose_name='first name')),
                ('last_name', models.CharField(blank=True, max_length=150, verbose_name='last name')),
                ('is_active', models.BooleanField(default=True, help_text='Designates whether this user should be treated as active. Unselect this instead of deleting accounts.', verbose_name='active')),
                ('username', models.CharField(max_length=128, unique=True, verbose_name='用户名')),
                ('chname', models.CharField(blank=True, max_length=254, verbose_name='中文名')),
                ('company', models.CharField(blank=True, max_length=128, verbose_name='公司')),
                ('qq', models.CharField(blank=True, max_length=32, verbose_name='QQ号')),
                ('phone', models.CharField(blank=True, max_length=64, verbose_name='手机号')),
                ('email', models.EmailField(blank=True, max_length=254, verbose_name='邮箱')),
                ('is_staff', models.BooleanField(default=False, help_text='普通管理员可以登录到admin', verbose_name='普通管理员')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, verbose_name='date joined')),
                ('role', models.CharField(default='0', help_text='用户角色表示字符串', max_length=32, verbose_name='用户角色')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'win_user',
            },
            managers=[
                ('objects', django.contrib.auth.models.UserManager()),
            ],
        ),
        migrations.CreateModel(
            name='Loignlog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('login_time', models.DateTimeField(verbose_name='登录时间')),
                ('login_browser', models.CharField(blank=True, max_length=200, null=True, verbose_name='登录浏览器')),
                ('login_ip', models.CharField(blank=True, max_length=50, null=True, verbose_name='用户登录ip')),
                ('login_host', models.CharField(blank=True, max_length=100, null=True, verbose_name='登录HOST')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='loginlog', to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '用户登录日志',
                'verbose_name_plural': '用户登录日志',
                'db_table': 'win_user_login_log',
            },
        ),
        migrations.CreateModel(
            name='WaUserProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text='Required. 64 characters or fewer. Letters, digits and underlined only.', max_length=64, validators=[django.core.validators.RegexValidator('^[a-zA-Z0-9_]+$', 'Enter a valid key. This value may contain only letters, numbers and underlined characters.', 'invalid')])),
                ('value', models.TextField()),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='property', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户属性',
                'verbose_name_plural': '用户属性',
                'db_table': 'win_user_property',
                'unique_together': {('user', 'key')},
            },
        ),
    ]
