# Generated by Django 4.2.3 on 2023-09-18 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_alter_wauser_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wauser',
            name='role',
            field=models.IntegerField(blank=True, help_text='用户角色表示字符串', null=True, verbose_name='用户角色'),
        ),
    ]
