# Generated by Django 4.2.3 on 2023-09-21 17:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('system', '0003_alter_systemdept_creator'),
        ('account', '0005_alter_wauser_is_staff_alter_wauser_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='wauser',
            name='role',
            field=models.ForeignKey(blank=True, help_text='用户角色', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user', to='system.systemrole'),
        ),
    ]
