# Generated by Django 4.2.3 on 2023-10-20 15:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_loignlog_login_addr_loignlog_login_os'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='loignlog',
            name='login_host',
        ),
        migrations.AddField(
            model_name='loignlog',
            name='login_user_agent',
            field=models.TextField(blank=True, null=True, verbose_name='userAgent'),
        ),
    ]
