# Generated by Django 4.2.3 on 2023-12-13 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0009_loignlog_login_city_loignlog_login_country_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wauser',
            name='role',
        ),
    ]
